# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flexinome' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for flexinome
  pod 'AudioKit', '~> 4.11'
  pod 'SpreadsheetView'
  pod 'KBNumberPad', '~> 1.0.1'

end
